<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWtsvvmw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWtsvvmw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWtsvvmw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWtsvvmw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWtsvvmw\appDevDebugProjectContainer([
    'container.build_hash' => 'Wtsvvmw',
    'container.build_id' => '5e00757e',
    'container.build_time' => 1598127700,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWtsvvmw');
