<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCu1bmxs\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCu1bmxs/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCu1bmxs.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCu1bmxs\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCu1bmxs\appProdProjectContainer([
    'container.build_hash' => 'Cu1bmxs',
    'container.build_id' => '6f3589a9',
    'container.build_time' => 1599508286,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCu1bmxs');
